Multiple worlds backup
nicolaschan/minecraft-backup pull request #2
Opened 2018-12-12 17:38 UTC by semklauke

Hey man!

Thanks for the script!
Bukkit and Spigot server save the nether and end dimension into separate folder,
so I added to option to backup multiple folders into either different folders or one folder.
The -i and -o can be used multiple times.

Sorry for my english! :D

2019-04-09 01:54 UTC, nicolaschan commented
So sorry it took me so long to get to this – I really appreciate your contribution! :) I've left a comment on the file I'd like to address before the merge, though.

2019-04-09 02:33 UTC, nicolaschan requested changes

2019-04-09 02:33 UTC, nicolaschan commented on backup.sh
> +  local BACKUPS=($(ls -r $BACKUP_DIRECTORY | grep $WORLD_NAME)) # List newest first
Is there a more robust way of filtering backups for a particular world? I can see this going wrong where one world is called `world` and another world is called `world_nether`. When `$WORLD_NAME="world"` grep will also return results for `world_nether` since `world` is a substring of `world_nether`.

2020-05-01 12:42 UTC, iMarv commented on backup.sh
> +  local BACKUPS=($(ls -r $BACKUP_DIRECTORY | grep $WORLD_NAME)) # List newest first
```suggestion
  local BACKUPS=($(ls -r $BACKUP_DIRECTORY | grep "$WORLD_NAME$")) # List newest first
```

Wouldn't this be sufficient @nicolaschan ?
Matches to the end of the string so `world_nether` should not be matching on `world`

2020-05-01 13:21 UTC, iMarv commented on backup.sh
> +  local BACKUPS=($(ls -r $BACKUP_DIRECTORY | grep $WORLD_NAME)) # List newest first
Nvm a bit more stuff to do, does not look like this was tested beforehand at all

2021-06-04 04:02 UTC, nicolaschan commented
Merged #22 which makes multiple worlds backup possible

2021-06-04 04:02 UTC, closed without merging